### ISSUE TITLE
Cannot instantiate interface SpecShaper\EncryptBundle\Encryptors\EncryptorInterface

### ISSUE THREAD

**Issue by Jeordy** [mogilvie/EncryptBundle#1]
When instantiate the EncryptorInterface in a controller, Symfony throws an exception:

CRITICAL11:11:00 | php | Cannot instantiate interface SpecShaper\EncryptBundle\Encryptors\EncryptorInterface
-- | -- | --
CRITICAL11:11:00 | request | Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Cannot instantiate interface SpecShaper\EncryptBundle\Encryptors\EncryptorInterface" at /Users/jeordy/Sites/TuffelCrm/src/CrmBundle/Controller/MagentoController.php line 41

**Comment by mogilvie** [comment]
Hi Jeordy,
I've updated the encrypt files, but not really done anything that would affect how the Factory creates the OpenSSL encryptor.

The EncryptorInterface is an alias for an EncryptorService built from the EncryptorFactory. At the moment the factory only creates an OpenSSl encryptor.

Do you have OpenSSL installed?

**Comment by Jeordy** [comment]
Hi Mark,

Thank you for replying so quickly. I will install the updated version and get back to you.

(OpenSSL is installed on my Mac)

Is it possible to auto decrypt when retreiving info with doctrine? This would come in handy when creating forms.

Kind regards,

Jeordy Bouck

________________________________
Van: Mark Ogilvie <notifications@github.com>
Verzonden: woensdag 28 februari 2018 13:50
Aan: mogilvie/EncryptBundle
CC: Jeordy; Author
Onderwerp: Re: [mogilvie/EncryptBundle] Cannot instantiate interface SpecShaper\EncryptBundle\Encryptors\EncryptorInterface (#1)


Hi Jeordy,
I've updated the encrypt files, but not really done anything that would affect how the Factory creates the OpenSSL encryptor.

The EncryptorInterface is an alias for an EncryptorService built from the EncryptorFactory. At the moment the factory only creates an OpenSSl encryptor.

Do you have OpenSSL installed?

**Comment by mogilvie** [comment]
Hi jeordy,
The subscriber decrypts the entity parameter on the doctrine load event. This is before you form renders. It then encrypts again on the flush event. You dont need to inject the encryptor interface for normal CRUD actions.

**Comment by mogilvie** [comment]
I just reread first message. You should be injecting the service interface into the controller action. Not instantiating inside the action.

**Comment by mogilvie** [comment]
Hi Jeordy, did this work out for you?
Can I close the issue?

**Comment by Jeordy** [comment]
Hi Mark,

It's working perfectly. Creating the service and then encrypt/decrtyp did the trick.

You can close the issue.

Kind regards,

Jeordy Bouck

________________________________
Van: Mark Ogilvie <notifications@github.com>
Verzonden: zondag 4 maart 2018 23:35
Aan: mogilvie/EncryptBundle
CC: Jeordy; Author
Onderwerp: Re: [mogilvie/EncryptBundle] Cannot instantiate interface SpecShaper\EncryptBundle\Encryptors\EncryptorInterface (#1)


Hi Jeordy, did this work out for you?
Can I close the issue?
