### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kr4ft3r** [mogilvie/EncryptBundle#23]
`composer require specshaper/encrypt-bundle dev-master` reports error during the recipe

```Symfony operations: 1 recipe (4218b4a3693097800c95fcd04c3354b4)
  - Configuring specshaper/encrypt-bundle (>=dev-master): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  TypeError {#583
!!    #message: "SpecShaper\EncryptBundle\Encryptors\OpenSslEncryptor::__construct(): Argument #2 ($key) must be of type string, null given, called in /home/kr4ft3r/code/symfony/airbridge2/vendor/specshaper/encrypt-bundle/Encryptors/EncryptorFactory.php on line 38"

**Comment by mogilvie** [comment]
Hi, you need to enter a key.

Copy the key into your .env file.

###> encrypt-bundle ###
ENCRYPT_KEY=<YOUR KEY HERE>
###< encrypt-bundle ###
And resolve in your parameters file.

// app/config/parameters.yml
    ...
    encrypt_key: '%env(resolve:ENCRYPT_KEY)%'

**Comment by mahesame** [comment]
In Symfony 6.1, you don't need parameters.yml. Put the "encrypt_key: '%env(resolve:ENCRYPT_KEY)%'" inside of app/config/services.yaml file below "parameters:". After that, try to install it again.
