### ISSUE TITLE
How to use attribute instead of  annotations 

### ISSUE THREAD

**Issue by memememetoo** [mogilvie/EncryptBundle#31]
I want to use attribute instead of annotation for "@Encrypted" .

What is the attribute equivalent of "@Encrypted" for entities?

**Comment by memememetoo** [comment]
I tried "#[Encrypted]", but its not working.
Its showing an error "data is missing".

**Comment by genseirin** [comment]
I'm also interested in support for attributes.

**Comment by memememetoo** [comment]
> I'm also interested in support for attributes.

Looks like the support is not there yet. I am using this bundle instead.
https://packagist.org/packages/michaeldegroot/doctrine-encrypt-bundle

it supports Attributes!!

**Comment by genseirin** [comment]
Thank you, @codenamerana

**Comment by genseirin** [comment]
> https://packagist.org/packages/michaeldegroot/doctrine-encrypt-bundle

But it doesn't seem to support Symfony 6. [EncryptBundle](https://github.com/mogilvie/EncryptBundle) has more recent updates and is compatible. Maybe it's easier to add attribute support here.

**Comment by memememetoo** [comment]
> > https://packagist.org/packages/michaeldegroot/doctrine-encrypt-bundle
> 
> But it doesn't seem to support Symfony 6. [EncryptBundle](https://github.com/mogilvie/EncryptBundle) has more recent updates and is compatible. Maybe it's easier to add attribute support here.

I am already using michaeldegroot in latest symfony 6. No issues.

**Comment by mogilvie** [comment]
Thanks for the suggestion. I have updated to support Attribute declaration of #[Encrypted] to master for the moment. Please let me know if this meets your needs and I will publish.

**Comment by memememetoo** [comment]
Thanks for the update :)

**Comment by genseirin** [comment]
perfect, thank you!

**Comment by WietseDevelto** [comment]
> Thanks for the suggestion. I have updated to support Attribute declaration of #[Encrypted] to master for the moment. Please let me know if this meets your needs and I will publish.

I am using the master branch and the annotation, but the data is still not encrypted. Am I missing something?

**Comment by mogilvie** [comment]
@WietseDevelto 
Have pushed the definition by Attribute to v3.0.2 release. Annotations are still supported but will are deprecated and will be removed in next major release.
