### ISSUE TITLE
symfony/console 6.1 deprecations

### ISSUE THREAD

**Issue by tsiatka** [mogilvie/EncryptBundle#32]
Hello !

Since I updated my project to Symfony 6.1, I have these two deprecation warnings in the profiler :

`Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "SpecShaper\EncryptBundle\Command\GenKeyCommand" class instead.`

`The "Symfony\Component\Console\Command\Command::$defaultName" property is considered final. You should not override it in "SpecShaper\EncryptBundle\Command\GenKeyCommand".`

Thank you

**Comment by mogilvie** [comment]
Hi @tsiatka,

Thanks for the notification. GenKeyCommand has been updated to use AsCommand attribute resolving the above deprecation notices.
