### ISSUE TITLE
Encryption works but not persisted

### ISSUE THREAD

**Issue by fylica** [mogilvie/EncryptBundle#41]
Hello,
I noticed encryption stopped persisting into database after upgrading to dev-master for the insert operations.
$encryptedValue seems ok on line DoctrineEncryptSubscriber.php:182 and it persisted fine if I comment line 203.
But unencrypted value is not persisted if I keep line 203 working.
Seems like it's related to https://github.com/mogilvie/EncryptBundle/issues/35#issue-1565907700

```
"doctrine/orm": "2.14",
"doctrine/doctrine-bundle": "2.8.3"
```

**Comment by mogilvie** [comment]
Resolved in dev-master, will push to v3.2 in next few days.
