### ISSUE TITLE
No longer work with symfony 6

### ISSUE THREAD

**Issue by timrasche** [mogilvie/EncryptBundle#42]
Uncaught Error: Class "Symfony\Component\HttpKernel\Bundle\AbstractBundle" not found in /vendor/specshaper/encrypt-bundle/src/SpecShaperEncryptBundle.php:16

**Comment by mogilvie** [comment]
Hi, which version are you using?
I'm currently running Encrypt bundle on three projects with "specshaper/encrypt-bundle": "^3.1.0", and "symfony/framework-bundle": "6.2.8"

**Comment by timrasche** [comment]
Version 6.2.

Dont get it... how can this work? Since Symfony 6.1 the class Symfony\Component\HttpKernel\Bundle\AbstractBundle is not longer available.

**Comment by feymo** [comment]
I'm currently using this bundle on SF 6.2.9 and no error so far too
I thought, on the contrary, that extending the `Symfony\Component\HttpKernel\Bundle\AbstractBundle` was introduced in SF6.1 to make bundle configuration easier ([ref](https://symfony.com/blog/new-in-symfony-6-1-simpler-bundle-extension-and-configuration)) or am i missing something 🤔  ?

**Comment by timrasche** [comment]
Ok guys, turns out that i really use 6.0 and there is some strange commit in this branch. Browse that repo (with branch 6.0) this class doesnt exist, but in 6.1 and 6.2 it exists. 

seems weird... 

thanks for support @all

**Comment by feymo** [comment]
`Symfony\Component\HttpKernel\Bundle\AbstractBundle` was introduced in 6.1 so in lower SF version this class indeed doesn't exist
But your issue raise something interesting, it seems like `v3` of this bundle will only work for 6.1 & above versions instead of 5.4|6 as described in the `README` file 🤔

**Comment by timrasche** [comment]
... to much this week. yes u'r right. sorry for that.
