### ISSUE TITLE
Made Twig support optional via config

### ISSUE THREAD

**Issue by d-kochnov-optimus** [mogilvie/EncryptBundle#51]
Looks like the **Twig** support feature can't be disabled at all. 

At the same time  the **Twig** bundle is not required in the `composer.json`.

So, the attempt to use the **EncryptBundle** on apps without **Twig** bundle leads to the 
`Attempted to load class "Twig_Extension" from the global namespace.`
error.

Can the **Twig** support feature be configurable? At lest in supported vesions.

**Comment by mogilvie** [comment]
Made optional in dev-master, will push to v3.2 in next few days.
