### ISSUE TITLE
Symfony 6.4 disabled annotations in framwork bundle and site crashed.

### ISSUE THREAD

**Issue by asifkhanpathan** [mogilvie/EncryptBundle#52]
in symfony 6.4 annotations are deprecated and disabled in framework but in  SpecShaper\EncryptBundle\Command\EncryptDatabaseCommand  service Doctrine\Common\Annotations\Reader is autoloading as annotationReader which is disabled result in site crashed with error 

`Cannot autowire service "SpecShaper\EncryptBundle\Command\EncryptDatabaseCommand": argument "$annotationReader" of method "__construct()" references interface "Doctrine\Common\Annotations\Reader" but no such service exists. Did you create a class that implements this interface?`

**Comment by mogilvie** [comment]
Reader command made optional in next version.
