### ISSUE TITLE
SQL error when decryping database with command

### ISSUE THREAD

**Issue by robertoperez18** [mogilvie/EncryptBundle#59]
Hi, I am using the library in order to encrypt some values of my SonataUserUser entity. Here is my code
```
    #[ORM\Column(type: Types::STRING, length: 255)]
    #[Assert\Regex(pattern: '/^\s*\S[\s\S]*$/')]
    #[Encrypted]
    private string $firstname;

    #[ORM\Column(name: 'first_lastname', type: Types::STRING, length: 255)]
    #[Assert\Regex(pattern: '/^\s*\S[\s\S]*$/')]
    #[Encrypted]
    private string $firstLastname;

    #[ORM\Column(name: 'second_lastname', type: Types::STRING, length: 255, nullable: true)]
    #[Assert\Regex(pattern: '/^\s*\S[\s\S]*$/')]
    #[Encrypted]
    private ?string $secondLastname = null;
```

But, whenever I run the command 
`bin/console encrypt:database decrypt`

I get the following error                                                                                                        
**An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'firstLastname' in 'field list'** 

Any help is appreciated, thank you very much in advance!

**Comment by mogilvie** [comment]
It will be due to the custom naming of the column in snake_case vs the php parameter name in camelCase.

I'm not working on this bundle at the moment, I will look to make updates in Jan 2025. If you wanted to make a pull request modifying the command I can look to incorporate that earlier.

**Comment by robertoperez18** [comment]
@mogilvie If i change this definition of the custom name and name it firstLastname, the error persists
`#[ORM\Column(name: 'firstLastname', type: Types::STRING, length: 255)]
    #[Assert\Regex(pattern: '/^\s*\S[\s\S]*$/')]
    #[Encrypted]
    private string $firstLastname;`

**Comment by robertoperez18** [comment]
never mind, I was not updating my database, it is working now
